// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::chassisLeftMotor;
std::shared_ptr<SpeedController> RobotMap::chassisRightMotor;
std::shared_ptr<RobotDrive> RobotMap::chassisRobotDrive2;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisLeftMotor.reset(new Talon(2));
    lw->AddActuator("Chassis", "LeftMotor", (Talon&) chassisLeftMotor);
    
    chassisRightMotor.reset(new Talon(6));
    lw->AddActuator("Chassis", "RightMotor", (Talon&) chassisRightMotor);
    
    chassisRobotDrive2.reset(new RobotDrive(chassisLeftMotor, chassisRightMotor));
    
    chassisRobotDrive2->SetSafetyEnabled(true);
        chassisRobotDrive2->SetExpiration(0.1);
        chassisRobotDrive2->SetSensitivity(0.5);
        chassisRobotDrive2->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
